export interface ProgrammaticTemplate {
  slug: string;
  type: 'industry' | 'country';
  name: string;
  headline: string;
  description: string;
  metaTitle: string;
  metaDescription: string;
  currency: string;
  currencySymbol: string;
  taxLabel: string;
  taxRate: number;
  complianceNote: string;
  flag?: string;
  industry?: string;
  sampleLineItems: { name: string; qty: number; rate: number }[];
  mandatoryFields: string[];
  faqs: { q: string; a: string }[];
  relatedSlugs: string[];
  matchingTemplateId: string;
}

export const PROGRAMMATIC_TEMPLATES: ProgrammaticTemplate[] = [
  // ─── INDUSTRY TEMPLATES (10) ───────────────────────────────────────────────
  {
    slug: 'photography-invoice-template',
    type: 'industry',
    name: 'Photography Invoice Template',
    headline: 'Professional Photography Invoice Template — Free to Download & Customize',
    description: 'Create professional photography invoices instantly. Includes session fees, editing hours, travel expenses, licensing, usage rights, and print packages in one clean invoice.',
    metaTitle: 'Free Photography Invoice Template | Professional Photographer Billing | Nobevra',
    metaDescription: 'Download a free photography invoice template for portrait, wedding, commercial, and event photographers. Includes usage rights, retouching hours, and print package line items.',
    currency: 'USD',
    currencySymbol: '$',
    taxLabel: 'Sales Tax',
    taxRate: 0,
    complianceNote: 'Photography is taxable in most US states. Digital delivery fees may have different rates. Check your state nexus rules.',
    industry: 'Photography & Videography',
    sampleLineItems: [
      { name: 'Wedding Photography Session (8 hours)', qty: 1, rate: 2500 },
      { name: 'Photo Editing & Retouching (4 hours)', qty: 4, rate: 75 },
      { name: 'Online Gallery Delivery & Hosting', qty: 1, rate: 150 },
      { name: 'Print Package (40 × 6"x4" prints)', qty: 1, rate: 350 },
    ],
    mandatoryFields: ['Invoice Number', 'Photographer Name & Address', 'Client Name & Address', 'Session Date & Location', 'Delivery Date', 'Usage Rights Clause', 'Payment Terms'],
    faqs: [
      { q: 'What should a photography invoice include?', a: 'A professional photography invoice should include your business name, address, and tax ID; the client details; a unique invoice number; session date and location; itemised line items for session fees, editing, prints, and travel; usage rights; payment terms; and your payment method or bank details.' },
      { q: 'Should photographers charge sales tax?', a: 'Whether photographers charge sales tax depends on the state or country. In the US, most states tax photography services and prints. Purely digital deliveries may be exempt in some states. Always verify your local nexus obligations.' },
      { q: 'What is a photography usage rights clause?', a: 'A usage rights clause specifies how the client is permitted to use the delivered images. It should define personal, commercial, or editorial use; exclusivity; and the geographic and time-frame limitations of the licence.' },
    ],
    relatedSlugs: ['freelance-graphic-designer-invoice-template', 'consulting-services-invoice-template'],
    matchingTemplateId: 'creative-1',
  },
  {
    slug: 'freelance-graphic-designer-invoice-template',
    type: 'industry',
    name: 'Graphic Designer Invoice Template',
    headline: 'Free Graphic Design Invoice Template — Bill Clients Professionally',
    description: 'Streamline billing for logo design, branding, web design, and illustration projects. Includes milestone-based payments, revision rounds, licensing transfer, and retainer clauses.',
    metaTitle: 'Free Graphic Designer Invoice Template | Freelance Design Billing | Nobevra',
    metaDescription: 'Free graphic design invoice template for freelance designers and agencies. Includes logo design, branding, web design, retainer, and milestone-based payment structure.',
    currency: 'USD',
    currencySymbol: '$',
    taxLabel: 'Sales Tax',
    taxRate: 0,
    complianceNote: 'Design services are taxable in some US states when a physical deliverable (print, CD) is provided. Purely digital design services may be exempt.',
    industry: 'Graphic Design & Creative Services',
    sampleLineItems: [
      { name: 'Brand Identity & Logo Design (Primary + Variations)', qty: 1, rate: 1800 },
      { name: 'Brand Guidelines Document', qty: 1, rate: 600 },
      { name: 'Social Media Kit (8 Templates)', qty: 8, rate: 75 },
      { name: 'Revision Rounds (Included in Package)', qty: 3, rate: 0 },
    ],
    mandatoryFields: ['Invoice Number', 'Designer Name & Business Address', 'Client Name & Address', 'Project Description', 'Milestone Deliverables', 'Revision Policy', 'IP / Copyright Transfer Clause', 'Payment Terms'],
    faqs: [
      { q: 'What should a graphic design invoice include?', a: 'A graphic design invoice should itemize each deliverable (logo files, style guide, templates), specify the number of included revision rounds, clarify intellectual property ownership transfer terms, and state payment milestones if billing in stages.' },
      { q: 'Should I invoice per project or per hour as a designer?', a: 'Project-based invoicing gives clients cost certainty and protects your time from scope creep. Hourly invoicing works well for open-ended editorial or maintenance retainers. Many experienced designers use a hybrid: fixed project fee plus an hourly rate for revisions beyond the agreed rounds.' },
    ],
    relatedSlugs: ['photography-invoice-template', 'consulting-services-invoice-template', 'web-developer-invoice-template'],
    matchingTemplateId: 'creative-2',
  },
  {
    slug: 'contractor-construction-invoice-template',
    type: 'industry',
    name: 'Contractor & Construction Invoice Template',
    headline: 'Free Contractor Invoice Template — Progress Billing & Lien Waivers',
    description: 'Issue progress billings, final completion invoices, and retention statements for construction, trades, and contracting projects. Includes materials, labour, subcontractor mark-up, and retainage.',
    metaTitle: 'Free Contractor Invoice Template | Construction Progress Billing | Nobevra',
    metaDescription: 'Free construction and contractor invoice template supporting progress billing, retention, lien waivers, materials, labour, and subcontractor billing for tradespeople and builders.',
    currency: 'USD',
    currencySymbol: '$',
    taxLabel: 'Sales Tax',
    taxRate: 0,
    complianceNote: 'Construction services and materials are subject to sales tax in most US states. Lump-sum contracts may be taxed differently from time-and-materials contracts.',
    industry: 'Construction & Trades',
    sampleLineItems: [
      { name: 'Foundation Excavation & Concrete Pour', qty: 1, rate: 8500 },
      { name: 'Framing Labour (320 man-hours)', qty: 320, rate: 65 },
      { name: 'Materials — Lumber, Fasteners & Sheathing', qty: 1, rate: 12200 },
      { name: 'Subcontractor — Electrical Rough-In', qty: 1, rate: 4800 },
      { name: 'Retention (10% withheld until completion)', qty: 1, rate: -3558 },
    ],
    mandatoryFields: ['Invoice Number', 'Contractor License Number', 'Project Address', 'Progress Billing Percentage Complete', 'Materials Breakdown', 'Labour Rates & Hours', 'Retention Amount', 'Lien Waiver Reference'],
    faqs: [
      { q: 'What is progress billing in construction invoicing?', a: 'Progress billing, also called schedule of values billing or percentage complete billing, allows contractors to invoice clients incrementally as defined project milestones are completed rather than waiting until the entire project is done.' },
      { q: 'What is a retention or retainage in a contractor invoice?', a: 'Retainage is a percentage (typically 5–10%) of each payment that the project owner withholds until substantial completion of the contract. It protects the owner against incomplete or defective work and is released upon final sign-off and lien waivers.' },
    ],
    relatedSlugs: ['consulting-services-invoice-template', 'legal-services-invoice-template'],
    matchingTemplateId: 'professional-1',
  },
  {
    slug: 'consulting-services-invoice-template',
    type: 'industry',
    name: 'Consulting Services Invoice Template',
    headline: 'Free Consulting Invoice Template — Management & IT Advisory Billing',
    description: 'Bill consulting engagements, strategy retainers, and advisory projects with clarity. Supports hourly, day-rate, fixed-fee, and outcome-based billing models for solo consultants, boutique firms, and enterprise advisory practices.',
    metaTitle: 'Free Consulting Invoice Template | Management & IT Consultant Billing | Nobevra',
    metaDescription: 'Professional consulting invoice template for management consultants, IT advisors, and strategy firms. Supports hourly, daily, retainer, and milestone billing models.',
    currency: 'USD',
    currencySymbol: '$',
    taxLabel: 'Sales Tax / VAT',
    taxRate: 0,
    complianceNote: 'Consulting services are generally subject to GST/VAT in most jurisdictions. In the US, consulting may be exempt from state sales tax — verify your state classification.',
    industry: 'Management & IT Consulting',
    sampleLineItems: [
      { name: 'Strategy Workshop Facilitation (2 days)', qty: 2, rate: 4500 },
      { name: 'Market Research & Competitive Analysis Report', qty: 1, rate: 3200 },
      { name: 'Implementation Support (Hourly)', qty: 18, rate: 350 },
      { name: 'Travel & Accommodation (Reimbursable)', qty: 1, rate: 820 },
    ],
    mandatoryFields: ['Invoice Number', 'Consultant Business Name & Address', 'Client Company & Contact', 'Engagement Reference Number', 'Deliverables & Scope Description', 'Billing Period', 'Payment Terms', 'Bank/Wire Transfer Details'],
    faqs: [
      { q: 'How should a consultant invoice clients?', a: 'Consultants should invoice with a unique invoice number, project reference, detailed description of services rendered in the billing period, the agreed billing model (hourly, daily, or fixed-fee), total amount due, payment terms (e.g. Net 15), and complete payment instructions.' },
      { q: 'When should a consultant invoice — before or after work?', a: 'For new clients or high-value engagements, invoice a 30–50% deposit upfront before commencing work. For ongoing retainers, invoice at the start of each period. For project-based work, invoice at defined milestones — typically 30% upfront, 40% at mid-point, 30% on delivery.' },
    ],
    relatedSlugs: ['web-developer-invoice-template', 'legal-services-invoice-template', 'contractor-construction-invoice-template'],
    matchingTemplateId: 'professional-2',
  },
  {
    slug: 'web-developer-invoice-template',
    type: 'industry',
    name: 'Web Developer Invoice Template',
    headline: 'Free Web Developer Invoice Template — Sprint, Milestone & Retainer Billing',
    description: 'Invoice for web design, application development, API integrations, and maintenance retainers. Supports Agile sprint billing, milestone-based payments, hosting reimbursements, and monthly maintenance packages.',
    metaTitle: 'Free Web Developer Invoice Template | Software & App Development Billing | Nobevra',
    metaDescription: 'Free invoice template for web developers, app developers, and software engineers. Covers Agile sprint billing, milestone invoicing, maintenance retainers, and API integrations.',
    currency: 'USD',
    currencySymbol: '$',
    taxLabel: 'Sales Tax',
    taxRate: 0,
    complianceNote: 'SaaS and downloaded software may be subject to sales tax in many US states, particularly after the Wayfair decision expanded economic nexus. Consult a tax professional.',
    industry: 'Software & Web Development',
    sampleLineItems: [
      { name: 'Sprint 3 — User Authentication & Dashboard Module', qty: 1, rate: 6400 },
      { name: 'API Integration — Stripe & Webhook Configuration', qty: 1, rate: 1800 },
      { name: 'QA Testing & Bug Fixes (28 hours)', qty: 28, rate: 95 },
      { name: 'Monthly Hosting & DevOps Maintenance (June)', qty: 1, rate: 450 },
    ],
    mandatoryFields: ['Invoice Number', 'Developer/Agency Name & Address', 'Client Company & Project Name', 'Sprint or Milestone Reference', 'Deliverables Completed', 'GitHub Repository Reference (optional)', 'Hosting Reimbursements', 'Payment Terms'],
    faqs: [
      { q: 'How do freelance developers structure invoices for long projects?', a: 'For multi-month projects, developers typically invoice in Agile sprints (every 2 weeks) or at key milestones (discovery, wireframes, development phases, QA, launch). A 25–50% upfront deposit protects against project abandonment. Maintenance retainers are billed monthly in advance.' },
      { q: 'Should web developers charge sales tax?', a: 'Web development services are not uniformly taxable. Purely professional services are often exempt, but delivering a tangible digital product, a downloaded application, or pre-written software may trigger sales tax obligations in many US states. Always consult a tax advisor for your specific situation.' },
    ],
    relatedSlugs: ['consulting-services-invoice-template', 'freelance-graphic-designer-invoice-template'],
    matchingTemplateId: 'professional-3',
  },
  {
    slug: 'legal-services-invoice-template',
    type: 'industry',
    name: 'Legal Services Invoice Template',
    headline: 'Free Law Firm Invoice Template — Legal Fee & Retainer Billing',
    description: 'Issue IOLTA-compliant legal fee invoices with timekeeper billing rates, disbursements, trust account balances, and retainer replenishment notices for law firms, solicitors, and independent legal practitioners.',
    metaTitle: 'Free Legal Services Invoice Template | Law Firm & Solicitor Billing | Nobevra',
    metaDescription: 'Professional legal invoice template for law firms, solicitors, and attorneys. Includes timekeeper rates, disbursements, trust account balance, and retainer statements.',
    currency: 'USD',
    currencySymbol: '$',
    taxLabel: 'N/A (Legal Services Exempt)',
    taxRate: 0,
    complianceNote: 'Legal services are generally VAT/GST exempt in most common law jurisdictions. However, UK solicitors must charge VAT. Always verify exemptions in your jurisdiction.',
    industry: 'Legal Services',
    sampleLineItems: [
      { name: 'Partner Time — Contract Drafting & Negotiation (4.5 hrs)', qty: 4.5, rate: 550 },
      { name: 'Associate Time — Legal Research & Due Diligence (8 hrs)', qty: 8, rate: 280 },
      { name: 'Court Filing Fees (Disbursement — Reimbursable)', qty: 1, rate: 450 },
      { name: 'Messenger & Process Server (Disbursement)', qty: 1, rate: 125 },
    ],
    mandatoryFields: ['Invoice Number', 'Bar Registration Number', 'Matter/Case Reference Number', 'Billing Period', 'Timekeeper Name & Rate', 'Disbursements Itemized', 'Trust Account Balance', 'Retainer Remaining Balance', 'Payment Terms'],
    faqs: [
      { q: 'What should a law firm invoice include?', a: 'A legal invoice must include the matter number, billing attorney name and bar number, detailed time entries with date, hours, and description of work, disbursements itemized separately, VAT if applicable, trust account balance, retainer used and remaining balance, and payment instructions.' },
      { q: 'What is a legal retainer on an invoice?', a: 'A legal retainer is an upfront fee paid by the client to secure legal representation. The law firm draws down against the retainer as work is performed and bills against it. When the retainer is depleted, the client replenishes it. The invoice should always show the retainer balance.' },
    ],
    relatedSlugs: ['consulting-services-invoice-template', 'contractor-construction-invoice-template'],
    matchingTemplateId: 'professional-4',
  },
  {
    slug: 'medical-healthcare-invoice-template',
    type: 'industry',
    name: 'Medical & Healthcare Invoice Template',
    headline: 'Free Medical Invoice Template — Private Practice & Healthcare Billing',
    description: 'Issue professional invoices for private practice consultations, therapy sessions, diagnostic procedures, and medical equipment. Includes CPT/procedure codes, insurance co-payment breakdowns, and HIPAA-compliant patient billing.',
    metaTitle: 'Free Medical Invoice Template | Private Practice & Healthcare Billing | Nobevra',
    metaDescription: 'Professional medical invoice template for doctors, therapists, and private clinics. Includes CPT codes, procedure fees, insurance adjustments, and HIPAA-compliant patient billing.',
    currency: 'USD',
    currencySymbol: '$',
    taxLabel: 'N/A (Medical Exempt)',
    taxRate: 0,
    complianceNote: 'Medical and healthcare services are generally VAT/sales tax exempt in most jurisdictions. Medical equipment may be taxable — confirm local healthcare exemption rules.',
    industry: 'Medical & Healthcare',
    sampleLineItems: [
      { name: 'Initial Consultation & Assessment (CPT 99204)', qty: 1, rate: 350 },
      { name: 'Follow-Up Consultation (CPT 99213)', qty: 2, rate: 185 },
      { name: 'Diagnostic Ultrasound (CPT 76815)', qty: 1, rate: 620 },
      { name: 'Less: Insurance Co-Payment Adjustment', qty: 1, rate: -280 },
    ],
    mandatoryFields: ['Invoice Number', 'Provider NPI Number', 'Patient Name & DOB', 'CPT / Procedure Codes', 'Date of Service', 'Insurance Claim Reference', 'Diagnosis Code (ICD-10)', 'Co-Payment / Patient Responsibility', 'Payment Due Date'],
    faqs: [
      { q: 'What is included in a medical invoice?', a: 'A medical invoice includes provider details and NPI number, patient name and date of birth, date of service, CPT (Current Procedural Terminology) codes for each procedure, fees, insurance adjustments, co-payments or deductibles owed by the patient, and payment instructions.' },
      { q: 'Are medical services exempt from VAT?', a: 'In most countries, essential medical and healthcare services are VAT or sales tax exempt. However, cosmetic procedures, elective treatments, and medical equipment may be taxable. Always verify applicable exemptions with a tax professional in your specific jurisdiction.' },
    ],
    relatedSlugs: ['legal-services-invoice-template', 'consulting-services-invoice-template'],
    matchingTemplateId: 'essentials-1',
  },
  {
    slug: 'real-estate-invoice-template',
    type: 'industry',
    name: 'Real Estate Invoice Template',
    headline: 'Free Real Estate Invoice Template — Agent Commission & Property Management Billing',
    description: 'Bill commission earnings, property management fees, tenant placement fees, and maintenance coordination charges. Compliant with real estate licensing disclosure requirements across major markets.',
    metaTitle: 'Free Real Estate Invoice Template | Agent Commission & Property Management | Nobevra',
    metaDescription: 'Professional real estate invoice template for agents, brokers, and property managers. Covers sale commissions, rental management fees, tenant placement, and maintenance billing.',
    currency: 'USD',
    currencySymbol: '$',
    taxLabel: 'Sales Tax / VAT',
    taxRate: 0,
    complianceNote: 'Real estate commissions are generally exempt from sales tax, but property management services may be taxable in some US states. UK estate agency fees attract 20% VAT.',
    industry: 'Real Estate & Property Management',
    sampleLineItems: [
      { name: 'Buyer Representation Commission (2.5% of $485,000 sale)', qty: 1, rate: 12125 },
      { name: 'Transaction Coordination Fee', qty: 1, rate: 450 },
      { name: 'Professional Photography & Virtual Tour', qty: 1, rate: 650 },
      { name: 'MLS Listing Fee', qty: 1, rate: 250 },
    ],
    mandatoryFields: ['Invoice Number', 'Agent License Number & Brokerage', 'Property Address & MLS Number', 'Transaction Date', 'Sale Price & Commission Rate', 'Co-Broker Split (if applicable)', 'Payment Terms'],
    faqs: [
      { q: 'How do real estate agents invoice their commission?', a: 'Real estate commission invoices should reference the property address, MLS number, transaction closing date, the agreed commission rate and amount, any co-broker splits, and the brokerage receiving the payment. Commission is typically paid directly from escrow at closing.' },
    ],
    relatedSlugs: ['consulting-services-invoice-template', 'legal-services-invoice-template'],
    matchingTemplateId: 'professional-5',
  },
  {
    slug: 'catering-events-invoice-template',
    type: 'industry',
    name: 'Catering & Events Invoice Template',
    headline: 'Free Catering Invoice Template — Event & Hospitality Billing',
    description: 'Invoice for weddings, corporate events, private dinners, and drop-off catering. Includes per-head pricing, food & beverage minimums, staffing fees, equipment rental, and service charges.',
    metaTitle: 'Free Catering Invoice Template | Event & Hospitality Billing | Nobevra',
    metaDescription: 'Professional catering invoice template for event caterers and hospitality businesses. Includes per-head pricing, staffing, beverage packages, venue, and service charges.',
    currency: 'USD',
    currencySymbol: '$',
    taxLabel: 'Sales Tax',
    taxRate: 8.25,
    complianceNote: 'Catering and food services are taxable in most US states. Prepared food is generally taxable while grocery-style food items may be exempt. Verify state-specific food taxation rules.',
    industry: 'Catering & Events',
    sampleLineItems: [
      { name: 'Corporate Lunch — 3-Course Buffet (85 guests @ $42/head)', qty: 85, rate: 42 },
      { name: 'Event Staffing — 4 Servers × 6 Hours', qty: 24, rate: 28 },
      { name: 'Equipment Rental — Chafing Dishes, Linens & Tableware', qty: 1, rate: 380 },
      { name: 'Gratuity (18% — Applied to Food & Staffing)', qty: 1, rate: 732.24 },
    ],
    mandatoryFields: ['Invoice Number', 'Catering Company Name & License', 'Event Date & Venue Address', 'Guest Count & Menu Package', 'Staffing Hours & Rates', 'Equipment Rental Items', 'Gratuity & Service Charge', 'Dietary Accommodation Notes', 'Deposit Received & Balance Due'],
    faqs: [
      { q: 'What should a catering invoice include?', a: 'A professional catering invoice should include the event date and venue, guest count, itemized food and beverage packages, staffing hours and rates, equipment rental, service charges or gratuity, applicable sales tax, any deposits already paid, and the final balance due.' },
    ],
    relatedSlugs: ['photography-invoice-template', 'consulting-services-invoice-template'],
    matchingTemplateId: 'creative-3',
  },
  {
    slug: 'auto-repair-invoice-template',
    type: 'industry',
    name: 'Auto Repair Invoice Template',
    headline: 'Free Auto Repair Invoice Template — Mechanic & Workshop Billing',
    description: 'Issue professional automotive repair invoices with labour hours, parts, OEM vs aftermarket breakdown, diagnostic fees, and warranty statements. Meets requirements for insurance claim documentation.',
    metaTitle: 'Free Auto Repair Invoice Template | Mechanic & Automotive Workshop Billing | Nobevra',
    metaDescription: 'Professional auto repair invoice template for mechanics, garages, and automotive service centres. Includes labour, parts, diagnostics, warranty, and insurance claim documentation.',
    currency: 'USD',
    currencySymbol: '$',
    taxLabel: 'Sales Tax',
    taxRate: 7.25,
    complianceNote: 'Auto repair labour and parts are generally subject to sales tax in most US states. Verify your state-specific rules for labour-only invoices vs parts and labour combined.',
    industry: 'Automotive Repair',
    sampleLineItems: [
      { name: 'Diagnostic Scan & Fault Code Analysis', qty: 1, rate: 120 },
      { name: 'Labour — Brake Pad & Rotor Replacement (2.5 hrs)', qty: 2.5, rate: 115 },
      { name: 'OEM Brake Pads — Front Axle Set', qty: 1, rate: 185 },
      { name: 'Brake Rotors × 2 (Front)', qty: 2, rate: 140 },
      { name: 'Labour — Oil Change & Filter (0.5 hr)', qty: 0.5, rate: 115 },
      { name: 'Synthetic Motor Oil 5W-30 (5 Quarts)', qty: 5, rate: 12 },
    ],
    mandatoryFields: ['Invoice Number', 'Workshop License & Business Name', 'Customer Name & Vehicle Details (Year/Make/Model/VIN)', 'Service Date', 'Labour Hours & Rate', 'Parts — OEM vs Aftermarket', 'Diagnostic Fee', 'Warranty Statement', 'Mileage In & Out'],
    faqs: [
      { q: 'What should an auto repair invoice include?', a: 'An auto repair invoice must include your shop name, license number, and contact info; the customer name and vehicle details (year, make, model, VIN, mileage); a detailed breakdown of all labour performed with hours and rates; all parts used with OEM or aftermarket designation; any diagnostic fees; sales tax; warranty information; and the total amount due.' },
    ],
    relatedSlugs: ['contractor-construction-invoice-template', 'medical-healthcare-invoice-template'],
    matchingTemplateId: 'professional-6',
  },

  // ─── COUNTRY / TAX JURISDICTION TEMPLATES (8) ──────────────────────────────
  {
    slug: 'uk-vat-invoice-template',
    type: 'country',
    name: 'UK VAT Invoice Template',
    headline: 'Free UK VAT Invoice Template — HMRC Compliant VAT Invoice',
    description: 'Create HMRC-compliant VAT invoices with the correct format for UK standard rate (20%), reduced rate (5%), and zero-rated supplies. Includes all mandatory fields required by the Value Added Tax Act 1994.',
    metaTitle: 'Free UK VAT Invoice Template | HMRC Compliant | Nobevra',
    metaDescription: 'Free UK VAT invoice template meeting all HMRC requirements for standard, reduced, and zero-rated supplies. Includes VAT registration number, tax point, and net/gross breakdown.',
    currency: 'GBP',
    currencySymbol: '£',
    taxLabel: 'VAT',
    taxRate: 20,
    flag: '🇬🇧',
    complianceNote: 'HMRC requires all VAT invoices to include: a sequential invoice number, your VAT registration number, tax point (date of supply), description of goods/services, VAT rate applied, net amount, VAT amount, and gross total.',
    sampleLineItems: [
      { name: 'Web Design & Development Services', qty: 1, rate: 4000 },
      { name: 'SEO Consulting Retainer (March)', qty: 1, rate: 1200 },
    ],
    mandatoryFields: ['Invoice Number (Sequential)', 'Supplier Name, Address & VAT Registration Number', 'Customer Name & Address', 'Tax Point (Date of Supply)', 'Description of Supply', 'VAT Rate Applied (%)', 'Net Amount (Excluding VAT)', 'VAT Amount', 'Gross Total (Including VAT)'],
    faqs: [
      { q: 'What are the mandatory fields on a UK VAT invoice?', a: 'HMRC requires the following on a valid VAT invoice: a unique sequential invoice number, your name and address, your VAT registration number, the invoice date, the tax point (date of supply if different), your customer name and address, a description of the goods or services, the rate of VAT charged, and the net amount, VAT amount, and gross total in pounds sterling.' },
      { q: 'When must I issue a VAT invoice in the UK?', a: 'VAT-registered businesses must issue a VAT invoice to another VAT-registered business within 30 days of the date of supply. For retail supplies to consumers, you only need to issue a VAT receipt if the customer requests one.' },
      { q: 'What is the threshold for UK VAT registration?', a: 'Businesses must register for VAT in the UK when their taxable turnover exceeds £90,000 in any rolling 12-month period (as of 2024). Voluntary registration is permitted below this threshold.' },
    ],
    relatedSlugs: ['eu-reverse-charge-invoice-template', 'south-africa-vat-invoice-template'],
    matchingTemplateId: 'essentials-2',
  },
  {
    slug: 'us-sales-tax-invoice-template',
    type: 'country',
    name: 'US Sales Tax Invoice Template',
    headline: 'Free US Sales Tax Invoice Template — Multi-State Sales Tax Billing',
    description: 'Create US sales tax invoices compliant with state nexus rules across all 50 states. Supports economic nexus after South Dakota v. Wayfair, use tax disclosures, and exemption certificate references.',
    metaTitle: 'Free US Sales Tax Invoice Template | Multi-State Nexus Billing | Nobevra',
    metaDescription: 'Free US sales tax invoice template for multi-state sellers and service providers. Compliant with economic nexus rules, exemption certificates, and state-specific tax rates.',
    currency: 'USD',
    currencySymbol: '$',
    taxLabel: 'Sales Tax',
    taxRate: 8.25,
    flag: '🇺🇸',
    complianceNote: 'US sales tax is governed at the state and local level — there is no federal sales tax. After South Dakota v. Wayfair (2018), remote sellers with economic nexus (usually $100K revenue or 200 transactions in a state) must collect and remit that state\'s sales tax.',
    sampleLineItems: [
      { name: 'E-Commerce Software SaaS Subscription (Annual)', qty: 1, rate: 3600 },
      { name: 'Professional Implementation Services', qty: 20, rate: 175 },
    ],
    mandatoryFields: ['Invoice Number', 'Seller Name, Address & State Sales Tax ID', 'Buyer Name & Shipping Address', 'Description of Taxable Goods/Services', 'State & Local Tax Rate Applied', 'Taxable Amount', 'Sales Tax Amount', 'Total Due', 'Exemption Certificate Number (if applicable)'],
    faqs: [
      { q: 'How do I calculate sales tax on a US invoice?', a: 'To calculate US sales tax: determine if you have nexus (physical presence or economic nexus) in the customer\'s state, identify the combined state + county + city tax rate for the customer\'s exact delivery address, apply that rate to the taxable sale price, and add the result to the invoice total.' },
      { q: 'Are services subject to sales tax in the US?', a: 'Services are not uniformly taxable in the US. Most states tax tangible personal property but differ significantly on services. Some states (e.g. South Dakota, New Mexico) tax most services broadly, while others (e.g. California) tax few services. Professional services like legal, medical, and accounting are generally exempt in most states.' },
    ],
    relatedSlugs: ['canada-gst-hst-invoice-template', 'uk-vat-invoice-template'],
    matchingTemplateId: 'essentials-3',
  },
  {
    slug: 'canada-gst-hst-invoice-template',
    type: 'country',
    name: 'Canada GST/HST Invoice Template',
    headline: 'Free Canada GST/HST Invoice Template — CRA Compliant Tax Invoice',
    description: 'Issue CRA-compliant invoices showing GST (5%), HST (13%–15% depending on province), or PST where applicable. Includes all mandatory CRA fields for registered businesses across all Canadian provinces.',
    metaTitle: 'Free Canada GST/HST Invoice Template | CRA Compliant | Nobevra',
    metaDescription: 'Free Canada GST/HST invoice template compliant with CRA requirements. Covers GST (5%), Ontario HST (13%), and Atlantic HST (15%). Includes CRA Business Number format.',
    currency: 'CAD',
    currencySymbol: 'CA$',
    taxLabel: 'HST (13% Ontario)',
    taxRate: 13,
    flag: '🇨🇦',
    complianceNote: 'CRA requires GST/HST invoices over CAD $100 to include: your Business Number (BN) with RT suffix, the rate of tax applied, the amount of GST/HST charged, and the total taxable supplies. Invoices under $30 only require basic information.',
    sampleLineItems: [
      { name: 'Brand Strategy Consulting (Q1 Retainer)', qty: 1, rate: 5500 },
      { name: 'Social Media Management (March)', qty: 1, rate: 1800 },
    ],
    mandatoryFields: ['Invoice Number', 'Supplier Name, Address & CRA Business Number (BN)', 'Customer Name & Address', 'Invoice Date', 'Description of Supplies', 'Total Supplies Before Tax', 'GST/HST Rate (5%, 13%, or 15%)', 'GST/HST Amount', 'Total Amount Payable'],
    faqs: [
      { q: 'What is a CRA Business Number and where does it go on an invoice?', a: 'A CRA Business Number (BN) is a unique 9-digit identifier assigned to your business by the Canada Revenue Agency. Your GST/HST account adds a \'RT 0001\' suffix (e.g. 123456789 RT 0001). This number must appear on all tax invoices issued to GST/HST registrants.' },
      { q: 'Do I need to charge HST or GST in every Canadian province?', a: 'It depends on the province. Ontario, Nova Scotia, New Brunswick, Newfoundland & Labrador, and PEI use HST (combined federal + provincial). Alberta, BC, Saskatchewan, Manitoba, and Quebec use GST (5% federal) plus separate PST or QST charged provincially. Northwest Territories, Nunavut, and Yukon apply only the federal GST at 5%.' },
    ],
    relatedSlugs: ['us-sales-tax-invoice-template', 'australia-tax-invoice-template'],
    matchingTemplateId: 'essentials-4',
  },
  {
    slug: 'australia-tax-invoice-template',
    type: 'country',
    name: 'Australia Tax Invoice Template',
    headline: 'Free Australia Tax Invoice Template — ATO GST Compliant',
    description: 'Issue ATO-compliant tax invoices showing 10% GST with correct ABN format. Includes all mandatory requirements for standard tax invoices above AUD $1,000 and simplified tax invoices below that threshold.',
    metaTitle: 'Free Australia Tax Invoice Template | ATO GST Compliant | Nobevra',
    metaDescription: 'Free Australian tax invoice template compliant with ATO requirements. Includes GST (10%), ABN, tax point, and net/gross breakdown for businesses registered for GST.',
    currency: 'AUD',
    currencySymbol: 'A$',
    taxLabel: 'GST (10%)',
    taxRate: 10,
    flag: '🇦🇺',
    complianceNote: 'For Australian tax invoices above AUD $1,000, the ATO requires: the words \'Tax Invoice\' at the top, seller name and ABN, buyer identity, date of issue, description of supply, GST amount, and total price including GST.',
    sampleLineItems: [
      { name: 'Website Redesign — Discovery & UX Phase', qty: 1, rate: 4500 },
      { name: 'Content Strategy & Copywriting (10 pages)', qty: 10, rate: 280 },
    ],
    mandatoryFields: ['The words "Tax Invoice" prominently displayed', 'Supplier Name & ABN', 'Buyer Name & ABN (for invoices over AUD $1,000)', 'Date of Issue', 'Description of Taxable Supply', 'GST Amount (10%)', 'Total Price Including GST'],
    faqs: [
      { q: 'What is an ABN and is it required on an Australian invoice?', a: 'An Australian Business Number (ABN) is an 11-digit unique identifier issued by the ATO. If you are registered for GST, your ABN must appear on all tax invoices. If a supplier does not quote their ABN on an invoice, the buyer may be required to withhold 47% (top marginal rate) of the payment under the PAYG withholding rules.' },
      { q: 'What is the GST registration threshold in Australia?', a: 'Businesses must register for GST if their current or projected annual turnover meets or exceeds AUD $75,000. Taxi and ride-share operators must register regardless of turnover. Voluntary registration is permitted for businesses below the threshold.' },
    ],
    relatedSlugs: ['uk-vat-invoice-template', 'canada-gst-hst-invoice-template'],
    matchingTemplateId: 'essentials-5',
  },
  {
    slug: 'nigeria-vat-invoice-template',
    type: 'country',
    name: 'Nigeria VAT Invoice Template',
    headline: 'Free Nigeria VAT Invoice Template — FIRS Compliant Tax Invoice',
    description: 'Issue FIRS-compliant VAT invoices showing 7.5% Value Added Tax and applicable Withholding Tax (WHT) deductions at source. Correct for B2B and B2C transactions within Nigeria.',
    metaTitle: 'Free Nigeria VAT Invoice Template | FIRS Compliant 7.5% VAT | Nobevra',
    metaDescription: 'Professional Nigeria VAT invoice template compliant with FIRS requirements. Includes 7.5% VAT, WHT deductions, TIN number format, and naira billing for B2B and B2C transactions.',
    currency: 'NGN',
    currencySymbol: '₦',
    taxLabel: 'VAT (7.5%)',
    taxRate: 7.5,
    flag: '🇳🇬',
    complianceNote: 'FIRS requires all taxable persons (turnover above NGN 25 million) to issue VAT invoices. Corporate clients are required to withhold 5% (for most services) or 10% (for professional services) at source and remit directly to FIRS.',
    sampleLineItems: [
      { name: 'Software Development Services (4 Months Retainer)', qty: 1, rate: 2400000 },
      { name: 'Cloud Infrastructure & Hosting', qty: 1, rate: 380000 },
    ],
    mandatoryFields: ['Invoice Number', 'Supplier Name, Address & TIN', 'Customer Name, Address & TIN', 'Invoice Date', 'Description of Taxable Supplies', 'Net Amount', 'VAT Amount (7.5%)', 'Gross Invoice Total', 'WHT Rate & Amount Withheld (if applicable)', 'Net Amount Receivable After WHT'],
    faqs: [
      { q: 'What is the current VAT rate in Nigeria?', a: 'Nigeria\'s current Value Added Tax rate is 7.5%, effective from February 1, 2020, following the Finance Act 2019 amendment to the VAT Act Cap V1 LFN 2004. This replaced the previous 5% rate.' },
      { q: 'What is Withholding Tax (WHT) in Nigeria and how does it affect my invoice?', a: 'Withholding Tax is a pre-payment of income tax deducted at source by corporate clients when paying for professional and consulting services. The applicable WHT rate is 5% for most services and 10% for professional fees (legal, accounting, consultancy). Your invoice should show the gross amount and the WHT amount withheld, with the net payment received being gross minus WHT.' },
    ],
    relatedSlugs: ['uk-vat-invoice-template', 'south-africa-vat-invoice-template'],
    matchingTemplateId: 'essentials-6',
  },
  {
    slug: 'eu-reverse-charge-invoice-template',
    type: 'country',
    name: 'EU Reverse Charge Invoice Template',
    headline: 'Free EU Reverse Charge VAT Invoice Template — B2B Cross-Border Billing',
    description: 'Issue compliant EU cross-border B2B invoices applying the Reverse Charge mechanism. When selling services to VAT-registered businesses in other EU member states, VAT is not charged by the supplier — the customer accounts for it in their local country.',
    metaTitle: 'Free EU Reverse Charge Invoice Template | Cross-Border B2B VAT | Nobevra',
    metaDescription: 'Professional EU reverse charge VAT invoice template for cross-border B2B services within the European Union. Includes mandatory EU VAT note, customer VAT number, and zero-rated format.',
    currency: 'EUR',
    currencySymbol: '€',
    taxLabel: 'Reverse Charge (0%)',
    taxRate: 0,
    flag: '🇪🇺',
    complianceNote: 'EU Reverse Charge applies to B2B services supplied to VAT-registered customers in another EU member state. The invoice MUST include the customer\'s VAT number and the statement: "VAT Reverse Charge — Customer to Account for VAT" per Article 194–199 of Council Directive 2006/112/EC.',
    sampleLineItems: [
      { name: 'Digital Marketing Strategy — Q2 Retainer (Berlin Client)', qty: 1, rate: 6800 },
      { name: 'Analytics Dashboard Development', qty: 1, rate: 2400 },
    ],
    mandatoryFields: ['Invoice Number', 'Supplier Name, Address & VAT Number', 'Customer Name, Address & VAT Number', 'Date of Supply', 'Description of Services', 'Net Amount in Euros', 'VAT Rate: 0% (Reverse Charge)', 'Mandatory Note: "VAT Reverse Charge — Customer to Account for VAT" (or local language equivalent)', 'Article 194/196 Reference'],
    faqs: [
      { q: 'When does the EU Reverse Charge mechanism apply?', a: 'The Reverse Charge applies to B2B services supplied between VAT-registered businesses in different EU member states under the General Rule (Article 44 of the VAT Directive). The supplier charges 0% VAT and the customer declares both input and output VAT in their own VAT return. It does NOT apply to B2C supplies, where normal destination country VAT rules apply.' },
      { q: 'What note must appear on a Reverse Charge invoice?', a: 'The invoice must clearly state: "Reverse charge — VAT to be accounted for by the customer" (or equivalent wording in the customer\'s language). It must also display the customer\'s valid EU VAT registration number. If the customer\'s VAT number is invalid or missing, you must charge your local VAT rate.' },
    ],
    relatedSlugs: ['uk-vat-invoice-template', 'uae-vat-invoice-template'],
    matchingTemplateId: 'platinum-1',
  },
  {
    slug: 'uae-vat-invoice-template',
    type: 'country',
    name: 'UAE VAT Invoice Template',
    headline: 'Free UAE VAT Invoice Template — FTA Compliant Tax Invoice',
    description: 'Issue Federal Tax Authority (FTA) compliant VAT invoices in the UAE and Saudi Arabia (ZATCA). Supports standard rate (5% UAE / 15% KSA), zero-rated supplies, and mandatory Arabic & English bilingual requirements.',
    metaTitle: 'Free UAE VAT Invoice Template | FTA Compliant 5% VAT | Nobevra',
    metaDescription: 'Professional UAE VAT invoice template compliant with FTA requirements. Includes 5% VAT, TRN number, bilingual Arabic/English format, and mandatory tax invoice fields.',
    currency: 'AED',
    currencySymbol: 'AED ',
    taxLabel: 'VAT (5%)',
    taxRate: 5,
    flag: '🇦🇪',
    complianceNote: 'The UAE FTA requires: the words \'Tax Invoice\' in Arabic and English, seller TRN, buyer TRN (if registered), date of supply, description of goods/services, taxable amount, VAT rate (5%), VAT amount, and gross total.',
    sampleLineItems: [
      { name: 'IT Infrastructure Consulting (Q1 Engagement)', qty: 1, rate: 45000 },
      { name: 'Cloud Migration Assessment Report', qty: 1, rate: 12000 },
    ],
    mandatoryFields: ['Invoice Number (Sequential)', 'Supplier Name, Address & TRN', 'Customer Name, Address & TRN (if registered)', 'Date of Supply', 'Description of Supply (Arabic & English)', 'Taxable Amount (AED)', 'VAT Rate (5%)', 'VAT Amount (AED)', 'Total Amount Payable (AED)'],
    faqs: [
      { q: 'What is a TRN number on a UAE VAT invoice?', a: 'A Tax Registration Number (TRN) is a 15-digit unique identifier issued by the UAE Federal Tax Authority (FTA) to businesses registered for VAT. It must appear on all tax invoices issued by VAT-registered businesses and is required when claiming input VAT credits.' },
      { q: 'What is the VAT registration threshold in the UAE?', a: 'Businesses must mandatorily register for UAE VAT if their taxable supplies and imports exceed AED 375,000 in the previous 12 months or are expected to exceed this threshold in the next 30 days. Voluntary registration is permitted for businesses with supplies above AED 187,500.' },
    ],
    relatedSlugs: ['uk-vat-invoice-template', 'eu-reverse-charge-invoice-template'],
    matchingTemplateId: 'platinum-2',
  },
  {
    slug: 'south-africa-vat-invoice-template',
    type: 'country',
    name: 'South Africa VAT Invoice Template',
    headline: 'Free South Africa VAT Invoice Template — SARS Compliant Tax Invoice',
    description: 'Issue SARS-compliant VAT invoices at the 15% standard rate for taxable supplies in South Africa. Includes all mandatory SARS fields including VAT registration number, tax period reference, and rand-denominated tax breakdown.',
    metaTitle: 'Free South Africa VAT Invoice Template | SARS Compliant 15% VAT | Nobevra',
    metaDescription: 'Professional South Africa VAT invoice template compliant with SARS requirements. Includes 15% VAT, VAT registration number, and rand-denominated tax breakdown for registered vendors.',
    currency: 'ZAR',
    currencySymbol: 'R ',
    taxLabel: 'VAT (15%)',
    taxRate: 15,
    flag: '🇿🇦',
    complianceNote: 'SARS requires tax invoices to include: supplier\'s name and VAT registration number, unique sequential number, date of supply, description of goods or services, quantity/volume, price excluding VAT, VAT amount at 15%, and total consideration including VAT.',
    sampleLineItems: [
      { name: 'Management Consulting Retainer (April)', qty: 1, rate: 85000 },
      { name: 'Leadership Development Workshop (Full Day)', qty: 1, rate: 22000 },
    ],
    mandatoryFields: ['Invoice Number (Unique Sequential)', 'Supplier Name, Address & VAT Registration Number', 'Recipient Name & Address (for B2B)', 'Date of Supply', 'Description of Taxable Supply', 'Quantity or Volume', 'Price Excluding VAT (Excl.)', 'VAT Amount at 15%', 'Total Including VAT (Incl.)'],
    faqs: [
      { q: 'What is the current VAT rate in South Africa?', a: 'The standard VAT rate in South Africa is 15%, effective from 1 April 2018 (increased from 14%). This applies to all taxable supplies of goods and services unless they are zero-rated or exempt. Zero-rated items include basic foodstuffs, exported goods, and certain financial services.' },
      { q: 'When must a South African business register for VAT?', a: 'A business must register as a VAT vendor with SARS once its taxable supplies in any 12-month period exceed or are expected to exceed R1,000,000. Voluntary registration is permitted for businesses with taxable supplies exceeding R50,000 in the preceding 12-month period.' },
    ],
    relatedSlugs: ['nigeria-vat-invoice-template', 'uk-vat-invoice-template'],
    matchingTemplateId: 'essentials-7',
  },
];

export function getAllProgrammaticSlugs(): string[] {
  return PROGRAMMATIC_TEMPLATES.map((t) => t.slug);
}

export function getTemplateBySlug(slug: string): ProgrammaticTemplate | undefined {
  return PROGRAMMATIC_TEMPLATES.find((t) => t.slug === slug);
}

export function getRelatedTemplates(slug: string): ProgrammaticTemplate[] {
  const template = getTemplateBySlug(slug);
  if (!template) return [];
  return template.relatedSlugs
    .map((s) => getTemplateBySlug(s))
    .filter((t): t is ProgrammaticTemplate => t !== undefined)
    .slice(0, 3);
}

export function getTemplatesByType(type: 'industry' | 'country'): ProgrammaticTemplate[] {
  return PROGRAMMATIC_TEMPLATES.filter((t) => t.type === type);
}
