-- Migration: Create Contract Signatures table for E-Signature audit trail
-- Description: Stores legally binding signature hashes, IPs, and timestamps

CREATE TABLE public.contract_signatures (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id uuid NOT NULL REFERENCES public.contracts(id) ON DELETE CASCADE,
    signer_name text NOT NULL,
    signer_email text NOT NULL,
    signature_data_url text NOT NULL, -- base64 image of the signature
    ip_address text,
    user_agent text,
    signed_at timestamp with time zone DEFAULT now() NOT NULL,
    audit_hash text NOT NULL -- cryptographic hash of the terms + signature
);

-- Indexes
CREATE INDEX idx_contract_signatures_contract_id ON public.contract_signatures USING btree (contract_id);

-- RLS
ALTER TABLE public.contract_signatures ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view signatures for their contracts" 
ON public.contract_signatures FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.contracts c 
        WHERE c.id = contract_signatures.contract_id AND c.user_id = auth.uid()
    )
);

CREATE POLICY "Public can insert signatures" 
ON public.contract_signatures FOR INSERT
WITH CHECK (true); -- allowed so external clients can sign
