export const termsMarkdown = `
# NOBEVRA TERMS OF SERVICE

**Effective Date:** August 8, 2026  
**Last Updated:** August 8, 2026

These Terms of Service ("Terms") constitute a legally binding agreement between you ("you," "your," "User," or "Customer") and The Noble's Technology Services, a company duly registered with the Corporate Affairs Commission (CAC) in Nigeria and operating the Nobevra platform ("Nobevra," "we," "us," or "our").

These Terms govern your access to and use of the Nobevra website, web application, mobile applications, APIs, software, services, features, content, and related products.

By creating an account, clicking to accept these Terms, accessing Nobevra, purchasing a subscription, generating or sending an invoice, using a premium feature, or otherwise using the Service, you acknowledge that you have read, understood, and agreed to these Terms.

If you do not agree with these Terms, you must not access or use Nobevra.

---

### 1. ABOUT NOBEVRA

Nobevra is a cloud-based business and productivity platform designed for freelancers, consultants, agencies, creators, businesses, and teams.

Depending on your plan and available features, Nobevra may provide tools including:

* Invoice creation and management
* Invoice templates (basic and premium)
* Quotes and estimates
* Recurring invoices and automated payment reminders
* Client relationship management (CRM)
* Client portals with live chat
* Expense tracking
* Receipt scanning and OCR
* Products, services and inventory management
* Payment links and payment integrations (including Flutterwave)
* Financial records, reporting and analytics
* Multi-currency functionality
* Digital business cards (NFC and QR)
* QR code generation and analytics
* Digital Product Passports
* Digital signatures and electronic-signature functionality
* Multi-user team workspaces and organization management
* AI-assisted functionality (AI assistant, AI voice invoice generation, receipt OCR extraction)
* Reports and analytics dashboards
* API and webhook functionality (Elite plan)
* Custom domain and white-label branding (Elite plan)
* Other business and productivity features introduced from time to time

Features are controlled by your subscription plan, geographic location, device, application version, integrations, and regulatory requirements or availability.

---

### 2. DEFINITIONS

For these Terms:

* **"Account"** means the account you create to access Nobevra.
* **"Business Data"** means information, records, documents, invoices, receipts, client information, products, services, expenses, images, files, QR data, business-card information, and other content submitted or generated by you through the Service.
* **"Customer Data"** means personal or business information concerning your customers, clients, contacts, employees, suppliers, or other persons that you provide to Nobevra.
* **"Content"** means text, images, documents, designs, files, information, audio, video, data, or other materials.
* **"Service"** means Nobevra's software, website, mobile applications, APIs, infrastructure, features, and related services.
* **"Subscription"** means a paid or free Nobevra plan providing access to specified features and usage allowances.
* **"Plan"** means the subscription tier selected by the Customer (Explorer, Pay-As-You-Go, Noble Pulse, or Noble Elite).
* **"Workspace"** means an individual or organizational environment within Nobevra.
* **"Third-Party Service"** means a service operated by a third party and integrated with or accessed through Nobevra.
* **"Entitlement"** means the specific features, usage allowances and quotas granted to you under your applicable Plan.

---

### 3. ELIGIBILITY

You must:

* Be legally capable of entering into a binding contract.
* Be at least 18 years old, unless applicable law permits otherwise.
* Have authority to enter into these Terms on behalf of a company, organization, partnership, or other entity where you are acting for such entity.
* Provide accurate registration information.
* Maintain accurate account information.

If you create an account on behalf of a business or organization, you represent that you have authority to bind that entity to these Terms. Nobevra is not intended to be used by children.

---

### 4. ACCOUNT REGISTRATION

You must create an Account to access certain features. You agree to:

* Provide accurate information and maintain current information.
* Protect your password and authentication credentials.
* Enable available security features where appropriate.
* Maintain control of your email address.
* Notify us promptly of unauthorized access.
* Not share your credentials or create accounts for fraudulent purposes.

You are responsible for activities conducted through your Account except where caused by Nobevra's proven failure to maintain reasonable security. Nobevra may require identity, business, payment, or verification information where reasonably necessary for security, fraud prevention, compliance, payment processing, or regulatory purposes.

---

### 5. ACCOUNT SECURITY

You are responsible for protecting your credentials. You must not share passwords; attempt to obtain another user's credentials; bypass authentication; exploit vulnerabilities; or attempt unauthorized access to another Workspace.

If you believe your Account has been compromised, contact us immediately at: **invoice@noblesworld.com.ng**

---

### 6. ACCEPTABLE USE

You may use Nobevra only for lawful and legitimate business purposes. You agree not to use Nobevra to: commit fraud; create fraudulent invoices; impersonate another person or business; facilitate money laundering or terrorism financing; distribute malware or ransomware; conduct phishing; spam users; infringe intellectual-property rights; violate privacy rights; harvest personal information unlawfully; exploit minors; circumvent subscription restrictions or manipulate usage quotas; reverse-engineer security mechanisms; interfere with other users; or violate applicable laws.

We may suspend or terminate Accounts involved in prohibited activities, subject to applicable law.

---

### 7. INVOICES AND BUSINESS RECORDS

Nobevra provides software for creating and managing invoices and related business records. You are solely responsible for: invoice accuracy; customer information; prices; taxes; discounts; currency; payment terms; invoice numbering; legal requirements; tax identification information; business registration information; statutory disclosures; and the legality of transactions.

Nobevra does not guarantee that an invoice generated using the Service satisfies every tax, accounting, commercial, or legal requirement applicable to your particular jurisdiction. You should obtain appropriate professional accounting or legal advice where necessary.

---

### 8. TAXES AND TAX COMPLIANCE

Nobevra may provide tax-related fields, calculations, reports, or functionality. Such functionality is provided as a software tool and does not constitute tax, accounting, or legal advice. You remain responsible for determining: applicable taxes; tax rates; tax registration; filing obligations; VAT/GST obligations; withholding obligations; cross-border tax obligations; and record-retention requirements.

---

### 9. PAYMENTS AND PAYMENT ARCHITECTURE

Nobevra may provide payment links, payment integrations, wallet-related functionality, payment tracking, or payment-related tools.

**Payment provider and architecture:** Payment transactions are processed through Flutterwave and other supported third-party payment providers. Nobevra uses a **tokenized payment architecture**:

* Nobevra does **not** store raw card numbers, CVVs, or full cardholder data on its servers.
* Card details are submitted directly to the payment provider's secure hosted environment.
* Nobevra stores only payment tokens (last 4 digits, card brand, expiry reference) returned by the payment provider, for the purpose of displaying your saved payment method.
* This architecture is designed to minimize Nobevra's exposure to cardholder data and to reduce the scope of applicable PCI DSS obligations.

Nobevra is not a bank, deposit-taking institution, money transmitter, payment processor, card issuer, or financial institution unless expressly stated otherwise. Third-party payment providers' own terms, privacy policies, fees, settlement rules, verification requirements, chargeback rules, and compliance requirements apply to transactions processed through them.

---

### 10. PAYMENT DISPUTES

Nobevra is generally not responsible for disputes between you and your customers concerning: unpaid invoices; refunds; chargebacks; payment reversals; failed transactions; delayed settlement; bank restrictions; payment-provider restrictions; or fraudulent customer transactions.

You are responsible for resolving commercial disputes with your customers unless the issue is directly caused by Nobevra's own breach of these Terms.

---

### 11. SUBSCRIPTION PLANS AND ENTITLEMENTS

Nobevra offers the following plans. **The authoritative, current pricing, currency, billing intervals, and availability are displayed on the applicable pricing page at** [https://nobevra.noblesworld.com.ng/pricing](https://nobevra.noblesworld.com.ng/pricing). The details below reflect the current commercial structure at the date of this document and may be updated from time to time.

#### Explorer (Free Plan)
A permanently free plan for freelancers getting started. Current entitlements include:
* Up to **50 invoices per month** (resets on the 1st of each month)
* **5 active clients**
* **3 estimates/quotes per month**
* **5 basic invoice templates**
* **100 MB document storage**
* Payment link generation and Flutterwave payment integration
* Expense tracking
* Email support

#### Pay-As-You-Go (PAYG)
A one-time purchase product (not a recurring subscription) designed for eligible free-tier users who need an occasional premium feature without subscribing. Each PAYG purchase unlocks:
* 1 premium invoice template (your choice)
* 1 client slot
* 1 QR business card (associated with that client)
* 1 Digital Product Passport (up to 3 images)
* Professional PDF download

PAYG is available only to users who do not have an active Noble Pulse or Noble Elite subscription, unless Nobevra expressly states otherwise. PAYG entitlements do not grant access to all premium features.

**Current price:** approximately USD $1.00 / NGN ₦1,500 per unit (prices displayed at checkout may differ based on applicable taxes, exchange rates and promotional offers).

#### Noble Pulse — $9.99/month | $99.00/year
A paid subscription for growing businesses. Includes everything in Explorer, plus:
* **Unlimited invoices and clients**
* **180+ premium invoice templates**
* Advanced invoice and client customization
* Recurring invoices and auto-reminders
* Client portal and live chat
* Inventory and product catalog
* Flutterwave payment integration
* Digital Business Cards (NFC and QR)
* Digital Product Passports
* Financial analytics dashboard
* **5 AI Voice Invoice uses per month**
* **5 Receipt Scans per month** (via AI OCR)
* **10 estimates per month**
* **1 GB document storage**
* Priority email support

#### Noble Elite — $24.99/month | $240.00/year
A higher-tier subscription for scaling businesses and teams. Includes everything in Noble Pulse, plus:
* **Multi-user team workspace**
* **Unlimited estimates**
* Advanced tax and compliance reporting
* **15 AI Voice Invoice + Receipt Scan uses per month**
* Vendor management
* **API access and webhooks**
* **Custom domain and white-label branding**
* Dedicated account manager
* Custom contracts and e-signature
* Priority 24/7 phone support
* Early access to new features
* Advanced autonomous SEO tools
* **5 GB document storage**

---

### 12. FEATURE ENTITLEMENTS AND USAGE QUOTAS

Access to Nobevra functionality is determined by your active subscription plan and entitlement status. Quotas include (but are not limited to): number of invoices per month; active clients; estimates per month; premium template access; AI voice invoice uses per month; receipt OCR uses per month; document storage; team members; QR codes and NFC business cards; Digital Product Passports; API requests; webhooks; custom domain access.

Usage limits may be enforced at the server and database level. **Attempting to circumvent, manipulate, reset, falsify, or otherwise bypass usage restrictions is a material breach of these Terms and may result in immediate Account suspension or termination.**

---

### 13. SUBSCRIPTION CHANGES

**Upgrade:** Additional features may become available immediately or after successful payment confirmation.

**Downgrade:** Certain features may become unavailable at the end of the applicable billing period. Downgrading does not delete your data immediately. However, some data or functionality may become read-only, inaccessible, or subject to the lower plan's limits. Nobevra will make commercially reasonable efforts to provide appropriate warnings before irreversible deletion resulting from plan limitations.

---

### 14. PAY-AS-YOU-GO RESTRICTIONS

PAYG purchases are intended for eligible users who do not hold an active Noble Pulse or Noble Elite subscription unless Nobevra expressly states otherwise. Each PAYG purchase is associated with a specific template, client slot, QR business card, or Digital Product Passport as described at the time of purchase. PAYG entitlements do not automatically grant access to all premium functionality.

---

### 15. SUBSCRIPTION BILLING, CONSENT, AND AUTOMATIC RENEWAL

Before completing a recurring subscription purchase, Nobevra will clearly disclose:

* **Plan name** (e.g., Noble Pulse)
* **Price** (e.g., $9.99/month or $99.00/year)
* **Billing frequency** (monthly or annual)
* **Next billing date**
* **Payment method** to be charged
* **Cancellation method**

Checkout confirmation buttons will clearly identify the commitment being made (for example: *"Start Noble Pulse — $9.99/month"*) rather than a generic or ambiguous action label. **Paid subscriptions automatically renew** at the end of each billing period unless you cancel before the applicable renewal date. Subscription charges are processed through the payment method and payment provider available during checkout.

---

### 16. CANCELLATION

You may cancel a subscription through the available account billing controls or by contacting Nobevra support. Cancellation prevents future renewal while normally allowing continued access to paid functionality through the end of the current paid billing period, unless otherwise stated. **Cancellation does not automatically erase your Account or Business Data.**

---

### 17. REFUNDS

Unless required by applicable law or expressly stated otherwise, subscription payments are non-refundable and partial billing periods are not automatically refunded. Nothing in this section limits mandatory consumer rights under applicable law. Where required by law, refund rights will apply.

---

### 18. FAILED PAYMENTS

If payment fails, Nobevra may: retry the payment; restrict premium features; place the subscription into a grace period; downgrade the Account to the Explorer (free) plan; suspend premium functionality; or terminate the subscription. The exact sequence depends on the payment provider and applicable plan.

---

### 19. FREE TRIALS AND PROMOTIONS

Nobevra may offer free trials, discounts, promotional credits, referral programs, or promotional subscriptions. Promotional offers may be limited to eligible users, may not be combined, may expire, and may have usage limitations. Material billing terms will be disclosed before payment is required.

---

### 20. CUSTOMER DATA OWNERSHIP

Subject to these Terms, you retain ownership of the Business Data and Customer Data that you submit to Nobevra. Nobevra does not acquire ownership of your business records merely because you store or process them through the Service. You are responsible for ensuring that you have the legal right to provide such information to Nobevra.

---

### 21. LICENSE TO PROCESS CUSTOMER DATA

You grant Nobevra a limited, worldwide, non-exclusive license to host, store, reproduce, transmit, process, format, and otherwise use your Business Data solely as reasonably necessary to: provide the Service; synchronize your Account; generate invoices; process requested operations; provide backups; provide support; maintain security; prevent fraud; troubleshoot; comply with law; and improve reliability. This license does not transfer ownership of your Business Data.

---

### 22. CLIENT AND THIRD-PARTY INFORMATION

If you upload information about clients, employees, suppliers, customers, or other people, you are responsible for ensuring that your collection and disclosure of that information complies with applicable privacy and data-protection laws. Where you act as a business customer using Nobevra to process information about your own customers, you may have independent obligations as a data controller.

---

### 23. PERSONAL DATA

Nobevra processes personal information as described in its [Privacy Policy](https://nobevra.noblesworld.com.ng/privacy). The Privacy Policy forms part of these Terms. Nobevra is subject to applicable privacy and data-protection obligations, including the Nigeria Data Protection Act 2023 (NDPA) and, where applicable, the GDPR, UK GDPR, and California privacy law (CCPA/CPRA).

---

### 24. DATA EXPORT

Where technically available, Nobevra may provide mechanisms for exporting Business Data. You should maintain appropriate independent backups of important business records.

---

### 25. DATA DELETION

You may request deletion of your Account subject to applicable law and legitimate retention requirements. Certain information may need to be retained for: legal compliance; fraud prevention; security; financial records; dispute resolution; enforcement of agreements; or regulatory requirements. Deletion may therefore not mean immediate physical deletion from every backup or system.

---

### 26. ACCOUNT DELETION AND ABUSE PREVENTION

Nobevra may apply reasonable anti-abuse measures to prevent repeated creation of accounts for the purpose of circumventing subscription limits, promotions, fraud controls, security controls, or abuse restrictions, subject to applicable data-protection law.

---

### 27. DIGITAL BUSINESS CARDS

Nobevra may allow users to create digital business cards and professional identity pages (available on Noble Pulse and Noble Elite). You are responsible for the information displayed. You must not use such identity tools to impersonate another individual, conduct fraud, distribute malicious links, or distribute prohibited content.

---

### 28. QR CODES

Nobevra supports multiple QR-code types. You are responsible for the destination and information encoded in your QR code. Nobevra does not guarantee that every QR code will work indefinitely if the destination URL or underlying service becomes unavailable.

---

### 29. QR ANALYTICS

Where QR analytics are available, Nobevra may collect technical and interaction data associated with QR-code usage, such as timestamp, approximate geographic location, device type, browser type, and interaction counts, as described in the Privacy Policy.

---

### 30. DIGITAL PRODUCT PASSPORTS

Where Digital Product Passport functionality is provided, Nobevra provides a software mechanism for organizing and presenting product information. Nobevra does not independently certify authenticity, origin, safety, regulatory compliance, or environmental claims. You are responsible for the accuracy and legality of information you publish.

---

### 31. RECEIPT SCANNING AND OCR

Nobevra may provide receipt scanning, image processing, OCR, or AI-assisted extraction. OCR and AI extraction can contain errors. You must verify extracted amounts, dates, vendors, tax information, currencies, and other financial data before relying on them.

---

### 32. ARTIFICIAL INTELLIGENCE FEATURES

Nobevra may provide AI-powered functionality, including: AI assistants; voice-assisted invoice generation; AI recommendations; business insights; automated extraction; and content generation.

AI-generated results may be inaccurate, incomplete, outdated, or inappropriate for your circumstances. You are responsible for reviewing AI-generated results before relying upon them. AI functionality does not constitute legal, tax, accounting, financial, investment, or medical advice.

---

### 33. AI INPUTS AND OUTPUTS

You should not submit confidential or sensitive information to AI features unless the relevant functionality expressly supports such information and the Privacy Policy permits its processing. You remain responsible for reviewing AI-generated documents before sending them to customers or using them for business decisions.

---

### 34. TEAM WORKSPACES (NOBLE ELITE)

Team workspace functionality is available on the Noble Elite plan. Workspace administrators may: invite members; assign roles; manage permissions; remove members; control access; and manage organizational information. Workspace administrators are responsible for ensuring permissions are appropriately configured.

---

### 35. ORGANIZATION ADMINISTRATORS

If you are an organization administrator, you represent that you have appropriate authority to administer the Workspace. Nobevra is not responsible for disputes between members of an organization concerning ownership, permissions, employment, access, or internal business relationships.

---

### 36. PROFESSIONAL SERVICES AND FINANCIAL INFORMATION

Nobevra provides software tools and does not provide professional accounting, tax, legal, investment, financial-planning, or banking services. Information shown in reports, dashboards, analytics, balances, projections, or financial summaries should be independently verified before making material decisions.

---

### 37. MULTI-CURRENCY

Nobevra may support multiple currencies and exchange-rate functionality. Exchange rates may be supplied by third-party data providers. Displayed exchange rates may differ from bank rates, payment-provider rates, or final settlement rates. Nobevra does not guarantee that displayed exchange rates are identical to the final settlement rate.

---

### 38. THIRD-PARTY SERVICES

Nobevra may integrate with third-party services. Third-party services are controlled by their respective providers. Their terms and privacy policies may apply. Nobevra is not responsible for third-party outages, policy changes, pricing changes, security incidents originating entirely within third-party infrastructure, or discontinued APIs.

---

### 39. PAYMENT PROVIDERS

Where Nobevra integrates with a payment provider, you may be required to create or maintain a separate account with that provider. The provider may independently conduct KYC, AML screening, transaction monitoring, fraud detection, settlement review, and account verification. Nobevra cannot guarantee that a payment provider will approve or maintain your account.

---

### 40. INTELLECTUAL PROPERTY

Nobevra and its licensors retain all rights in software, source code, architecture, UI, designs, trademarks, logos, graphics, documentation, platform content, algorithms, proprietary systems, databases, workflows, and branding. Except where expressly permitted, you may not copy, reproduce, distribute, sell, sub-license, modify, reverse-engineer, create derivative works, or commercially exploit Nobevra's proprietary materials.

---

### 41. USER CONTENT

You retain rights to content you upload. You represent that you have the necessary rights to upload that content. You must not upload content that infringes another person's copyright, trademark, privacy, publicity rights, trade secrets, or other intellectual-property rights.

---

### 42. FEEDBACK

If you submit suggestions, recommendations, feature requests, or feedback, you grant Nobevra permission to use that feedback without compensation or attribution, unless prohibited by law.

---

### 43. OPEN-SOURCE SOFTWARE

Nobevra may contain open-source components subject to separate open-source licenses. Nothing in these Terms removes rights granted to you under applicable open-source licenses.

---

### 44. AVAILABILITY

We aim to provide a reliable service but do not guarantee uninterrupted availability. The Service may occasionally be unavailable because of maintenance, upgrades, security events, infrastructure failures, third-party outages, internet failures, or force majeure.

---

### 45. BETA AND EXPERIMENTAL FEATURES

Nobevra may introduce beta, preview, experimental, or early-access functionality. Such features may change, become unavailable, contain bugs, or produce inaccurate results. You use experimental functionality at your own risk.

---

### 46. MOBILE APPLICATIONS

Nobevra may provide mobile applications for Android, iOS, and other supported platforms. You must comply with Nobevra Terms and applicable app-store terms. Updates may be required to continue using certain functionality.

---

### 47. API AND WEBHOOKS (NOBLE ELITE)

API and webhook functionality is available to Noble Elite subscribers. You must protect API credentials; avoid exposing secrets; comply with rate limits; use APIs lawfully; avoid abusive traffic; and respect security requirements. Nobevra may revoke API access where necessary to protect the platform.

---

### 48. SECURITY

Nobevra implements reasonable technical and organizational security measures appropriate to the nature of the Service. However, no internet service can guarantee absolute security. You acknowledge that internet transmissions may involve risk and you are responsible for maintaining your credentials. Security vulnerabilities should be responsibly reported to Nobevra.

---

### 49. CONFIDENTIALITY

Where appropriate, each party should protect confidential information received from the other. Enterprise customers may enter into a separate confidentiality agreement where required.

---

### 50. DISCLAIMER OF WARRANTIES

To the maximum extent permitted by applicable law, Nobevra provides the Service on an **"as available"** and **"as is"** basis. We do not guarantee that the Service will always be available, error-free, or that AI outputs or OCR results will always be accurate. Mandatory statutory warranties and consumer rights are not excluded where they cannot legally be excluded.

---

### 51. LIMITATION OF LIABILITY

To the maximum extent permitted by applicable law, Nobevra shall not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages arising from your use of the Service, including: loss of profits; loss of revenue; loss of business opportunities; loss of goodwill; business interruption; loss resulting from unpaid invoices; or loss caused by third-party payment providers.

Where permitted by law, Nobevra's aggregate liability relating to the Service shall be limited to the greater of: **(a)** amounts you paid to Nobevra during the twelve months immediately preceding the event giving rise to the claim; or **(b)** US$100. This limitation does not apply where prohibited by applicable law or where liability cannot legally be limited.

---

### 52. INDEMNIFICATION

To the extent permitted by law, you agree to defend, indemnify, and hold harmless Nobevra, The Noble's Technology Services, its officers, employees, contractors, affiliates, and service providers from claims arising from: your unlawful use of Nobevra; your violation of these Terms; your Business Data; infringement caused by your content; fraudulent activity; misuse of payment functionality; or violation of another person's rights.

---

### 53. SUSPENSION

Nobevra may temporarily suspend an Account where reasonably necessary to: protect security; investigate fraud; prevent abuse; comply with law; respond to a security incident; address payment failure; or prevent harm to other users. Where reasonably possible, we will provide notice and an opportunity to resolve the issue.

---

### 54. TERMINATION BY NOBEVRA

We may terminate an Account where: you materially breach these Terms; you engage in fraudulent activity; you repeatedly violate the Terms; your activity threatens platform security; required by law; or continuing the Account creates material legal or security risk. Termination does not remove rights or obligations that accrued before termination.

---

### 55. TERMINATION BY YOU

You may stop using Nobevra at any time. You may request Account deletion according to the applicable account-deletion procedure. Subscription cancellation and Account deletion are separate actions unless otherwise stated.

---

### 56. EFFECT OF TERMINATION

After termination: access may cease; premium functionality may be disabled; API credentials may be revoked; team access may be removed; and certain data may be retained where legally required. Where available, we may provide a reasonable period for data export.

---

### 57. COPYRIGHT COMPLAINTS

If you believe content hosted through Nobevra infringes your copyright, contact: **invoice@noblesworld.com.ng** with sufficient information to identify the copyrighted work, the allegedly infringing material, your ownership or authorization, your contact details, and the basis of your claim.

---

### 58. TRADEMARKS

"Nobevra" and associated branding are trademarks or protected brand assets. You may not use Nobevra branding in a manner suggesting endorsement, partnership, sponsorship, or affiliation without written permission.

---

### 59. INTERNATIONAL USE

Nobevra may be accessible internationally. However, we do not represent that every feature is legally or technically available in every country. You are responsible for determining whether your use of Nobevra complies with the laws applicable to you. Certain features may be restricted because of sanctions, payment restrictions, local laws, data-protection requirements, export controls, or regulatory requirements.

---

### 60. REGULATORY COMPLIANCE APPROACH

Nobevra maintains a global privacy and compliance framework designed to support applicable data-protection, security and regulatory requirements in the jurisdictions in which our services operate. Specific legal obligations may vary depending on jurisdiction, customer role, processing activity and applicable law. Nobevra does not represent that it complies with every law in every jurisdiction worldwide. Where applicable law imposes mandatory requirements, those requirements take precedence over conflicting provisions in these Terms.

---

### 61. EXPORT CONTROLS AND SANCTIONS

You must not use Nobevra in violation of applicable sanctions, export-control laws, or restrictions imposed by applicable authorities. Nobevra may restrict access where reasonably necessary to comply with applicable sanctions or legal requirements.

---

### 62. GOVERNING LAW

These Terms shall be governed by the laws of the Federal Republic of Nigeria, except to the extent mandatory laws of your jurisdiction require otherwise. Nothing in this section is intended to deprive consumers of mandatory legal protections available in their jurisdiction.

---

### 63. DISPUTE RESOLUTION

We encourage users to contact Nobevra first at **invoice@noblesworld.com.ng** so that disputes can be resolved informally. Where a dispute cannot be resolved informally, the parties may pursue available legal remedies under applicable law. Nothing in these Terms prevents a consumer from exercising mandatory statutory rights or bringing a claim before a legally competent regulatory or judicial authority where applicable.

---

### 64. CONSUMER RIGHTS

Nothing in these Terms is intended to exclude or restrict consumer rights that cannot lawfully be excluded. Nobevra will comply with mandatory consumer-protection requirements applicable to the transaction.

---

### 65. ELECTRONIC COMMUNICATIONS

You agree that Nobevra may communicate with you electronically regarding: Account security; transactions; subscriptions; invoices; service notices; product updates; legal notices; and support. Electronic communications may satisfy legal requirements for written communications where permitted by applicable law.

---

### 66. ELECTRONIC SIGNATURES

Where applicable, electronic acceptance, checkbox confirmation, digital signature, or other electronic authentication may constitute your agreement to these Terms.

---

### 67. CHANGES TO THESE TERMS

We may update these Terms periodically. When material changes are made, we may provide notice through the Service, email, Account notifications, or other reasonable methods. The updated Terms will identify the revised effective date. Your continued use after the effective date may constitute acceptance where legally permitted.

---

### 68. CHANGES TO THE SERVICE

Nobevra may: introduce features; remove obsolete features; modify interfaces; change infrastructure; change usage limits; modify integrations; or discontinue features. Where a material change substantially reduces a paid service, we will provide notice where reasonably required by applicable law or contract.

---

### 69. ASSIGNMENT

You may not transfer your rights or obligations under these Terms without our prior written consent. Nobevra may transfer these Terms in connection with a merger, acquisition, restructuring, sale of assets, or corporate reorganization.

---

### 70. FORCE MAJEURE

Nobevra will not be responsible for delay or failure caused by circumstances beyond reasonable control, including: natural disasters; war; terrorism; civil unrest; government actions; internet outages; infrastructure failures; major cyber incidents; telecommunications failures; power-grid failures; or third-party service failures.

---

### 71. SEVERABILITY

If any provision of these Terms is determined to be invalid or unenforceable, the remaining provisions will remain effective to the extent permitted by law.

---

### 72. NO WAIVER

Failure to enforce a provision does not constitute a waiver of our right to enforce it later.

---

### 73. ENTIRE AGREEMENT

These Terms, together with the Privacy Policy, applicable subscription terms, and other documents expressly incorporated by reference, constitute the agreement between you and Nobevra concerning the Service.

---

### 74. ORDER OF PRECEDENCE

If there is a conflict between these Terms and a separate written agreement signed with an enterprise customer, the signed enterprise agreement will control to the extent of the conflict. Mandatory applicable law will prevail over conflicting contractual provisions where required.

---

### 75. CONTACT INFORMATION

**Service:** Nobevra  
**Legal Entity:** The Noble's Technology Services  
**Website:** [https://nobevra.noblesworld.com.ng](https://nobevra.noblesworld.com.ng)  
**Email:** invoice@noblesworld.com.ng  
**Legal inquiries:** legal@noblesworld.com.ng  
**Privacy / DPO:** privacy@noblesworld.com.ng  

---

### 76. RELATED LEGAL DOCUMENTS

Users should also review:

* [Privacy Policy](https://nobevra.noblesworld.com.ng/privacy)
* [Cookie Policy](https://nobevra.noblesworld.com.ng/cookies)
* [Subprocessor List](https://nobevra.noblesworld.com.ng/subprocessors)
* [Data Processing Agreement (DPA)](https://nobevra.noblesworld.com.ng/dpa)
* [Security Policy](https://nobevra.noblesworld.com.ng/security)
* [AI & Responsible AI Policy](https://nobevra.noblesworld.com.ng/ai-policy)
* [Compliance Hub](https://nobevra.noblesworld.com.ng/compliance)
`;
