export interface Currency {
    code: string;
    symbol: string;
    label: string;
}

export const CURRENCIES: Currency[] = [
    { code: 'USD', symbol: '$', label: 'US Dollar' },
    { code: 'EUR', symbol: '€', label: 'Euro' },
    { code: 'GBP', symbol: '£', label: 'British Pound' },
    { code: 'NGN', symbol: '₦', label: 'Nigerian Naira' },
    { code: 'GHS', symbol: 'GH₵', label: 'Ghanaian Cedi' },
    { code: 'KES', symbol: 'KSh', label: 'Kenyan Shilling' },
    { code: 'ZAR', symbol: 'R', label: 'South African Rand' },
    { code: 'CAD', symbol: 'CA$', label: 'Canadian Dollar' },
    { code: 'AUD', symbol: 'A$', label: 'Australian Dollar' },
    { code: 'JPY', symbol: '¥', label: 'Japanese Yen' },
    { code: 'CNY', symbol: '¥', label: 'Chinese Yuan' },
    { code: 'INR', symbol: '₹', label: 'Indian Rupee' },
    { code: 'AED', symbol: 'د.إ', label: 'UAE Dirham' },
    { code: 'AFN', symbol: '؋', label: 'Afghan Afghani' },
    { code: 'ALL', symbol: 'L', label: 'Albanian Lek' },
    { code: 'AMD', symbol: '֏', label: 'Armenian Dram' },
    { code: 'ANG', symbol: 'ƒ', label: 'Netherlands Antillean Guilder' },
    { code: 'AOA', symbol: 'Kz', label: 'Angolan Kwanza' },
    { code: 'ARS', symbol: '$', label: 'Argentine Peso' },
    { code: 'AWG', symbol: 'ƒ', label: 'Aruban Florin' },
    { code: 'AZN', symbol: '₼', label: 'Azerbaijani Manat' },
    { code: 'BAM', symbol: 'KM', label: 'Bosnia and Herzegovina Mark' },
    { code: 'BBD', symbol: '$', label: 'Barbadian Dollar' },
    { code: 'BDT', symbol: '৳', label: 'Bangladeshi Taka' },
    { code: 'BGN', symbol: 'лв', label: 'Bulgarian Lev' },
    { code: 'BHD', symbol: '.د.ب', label: 'Bahraini Dinar' },
    { code: 'BIF', symbol: 'FBu', label: 'Burundian Franc' },
    { code: 'BMD', symbol: '$', label: 'Bermudian Dollar' },
    { code: 'BND', symbol: '$', label: 'Brunei Dollar' },
    { code: 'BOB', symbol: '$b', label: 'Bolivian Boliviano' },
    { code: 'BRL', symbol: 'R$', label: 'Brazilian Real' },
    { code: 'BSD', symbol: '$', label: 'Bahamian Dollar' },
    { code: 'BTN', symbol: 'Nu.', label: 'Bhutanese Ngultrum' },
    { code: 'BWP', symbol: 'P', label: 'Botswanan Pula' },
    { code: 'BYN', symbol: 'Br', label: 'Belarusian Ruble' },
    { code: 'BZD', symbol: 'BZ$', label: 'Belize Dollar' },
    { code: 'CDF', symbol: 'FC', label: 'Congolese Franc' },
    { code: 'CHF', symbol: 'CHF', label: 'Swiss Franc' },
    { code: 'CLP', symbol: '$', label: 'Chilean Peso' },
    { code: 'COP', symbol: '$', label: 'Colombian Peso' },
    { code: 'CRC', symbol: '₡', label: 'Costa Rican Colón' },
    { code: 'CUC', symbol: '$', label: 'Cuban Convertible Peso' },
    { code: 'CUP', symbol: '₱', label: 'Cuban Peso' },
    { code: 'CVE', symbol: '$', label: 'Cape Verdean Escudo' },
    { code: 'CZK', symbol: 'Kč', label: 'Czech Koruna' },
    { code: 'DJF', symbol: 'Fdj', label: 'Djiboutian Franc' },
    { code: 'DKK', symbol: 'kr', label: 'Danish Krone' },
    { code: 'DOP', symbol: 'RD$', label: 'Dominican Peso' },
    { code: 'DZD', symbol: 'د.ج', label: 'Algerian Dinar' },
    { code: 'EGP', symbol: '£', label: 'Egyptian Pound' },
    { code: 'ERN', symbol: 'Nfk', label: 'Eritrean Nakfa' },
    { code: 'ETB', symbol: 'Br', label: 'Ethiopian Birr' },
    { code: 'FJD', symbol: '$', label: 'Fijian Dollar' },
    { code: 'FKP', symbol: '£', label: 'Falkland Islands Pound' },
    { code: 'FOK', symbol: 'kr', label: 'Faroese Króna' },
    { code: 'GEL', symbol: '₾', label: 'Georgian Lari' },
    { code: 'GGP', symbol: '£', label: 'Guernsey Pound' },
    { code: 'GIP', symbol: '£', label: 'Gibraltar Pound' },
    { code: 'GMD', symbol: 'D', label: 'Gambian Dalasi' },
    { code: 'GNF', symbol: 'FG', label: 'Guinean Franc' },
    { code: 'GTQ', symbol: 'Q', label: 'Guatemalan Quetzal' },
    { code: 'GYD', symbol: '$', label: 'Guyanese Dollar' },
    { code: 'HKD', symbol: 'HK$', label: 'Hong Kong Dollar' },
    { code: 'HNL', symbol: 'L', label: 'Honduran Lempira' },
    { code: 'HRK', symbol: 'kn', label: 'Croatian Kuna' },
    { code: 'HTG', symbol: 'G', label: 'Haitian Gourde' },
    { code: 'HUF', symbol: 'Ft', label: 'Hungarian Forint' },
    { code: 'IDR', symbol: 'Rp', label: 'Indonesian Rupiah' },
    { code: 'ILS', symbol: '₪', label: 'Israeli New Shekel' },
    { code: 'IMP', symbol: '£', label: 'Manx Pound' },
    { code: 'IQD', symbol: 'ع.د', label: 'Iraqi Dinar' },
    { code: 'IRR', symbol: '﷼', label: 'Iranian Rial' },
    { code: 'ISK', symbol: 'kr', label: 'Icelandic Króna' },
    { code: 'JEP', symbol: '£', label: 'Jersey Pound' },
    { code: 'JMD', symbol: 'J$', label: 'Jamaican Dollar' },
    { code: 'JOD', symbol: 'ا.د', label: 'Jordanian Dinar' },
    { code: 'KHR', symbol: '៛', label: 'Cambodian Riel' },
    { code: 'KMF', symbol: 'CF', label: 'Comorian Franc' },
    { code: 'KPW', symbol: '₩', label: 'North Korean Won' },
    { code: 'KRW', symbol: '₩', label: 'South Korean Won' },
    { code: 'KWD', symbol: 'د.ك', label: 'Kuwaiti Dinar' },
    { code: 'KYD', symbol: '$', label: 'Cayman Islands Dollar' },
    { code: 'KZT', symbol: '₸', label: 'Kazakhstani Tenge' },
    { code: 'LAK', symbol: '₭', label: 'Laotian Kip' },
    { code: 'LBP', symbol: 'ل.ل', label: 'Lebanese Pound' },
    { code: 'LKR', symbol: '₨', label: 'Sri Lankan Rupee' },
    { code: 'LRD', symbol: '$', label: 'Liberian Dollar' },
    { code: 'LSL', symbol: 'M', label: 'Lesotho Loti' },
    { code: 'LYD', symbol: 'ل.د', label: 'Libyan Dinar' },
    { code: 'MAD', symbol: 'د.م.', label: 'Moroccan Dirham' },
    { code: 'MDL', symbol: 'L', label: 'Moldovan Leu' },
    { code: 'MGA', symbol: 'Ar', label: 'Malagasy Ariary' },
    { code: 'MKD', symbol: 'ден', label: 'Macedonian Denar' },
    { code: 'MMK', symbol: 'K', label: 'Myanmar Kyat' },
    { code: 'MNT', symbol: '₮', label: 'Mongolian Tughrik' },
    { code: 'MOP', symbol: 'MOP$', label: 'Macanese Pataca' },
    { code: 'MRU', symbol: 'UM', label: 'Mauritanian Ouguiya' },
    { code: 'MUR', symbol: '₨', label: 'Mauritian Rupee' },
    { code: 'MVR', symbol: 'Rf', label: 'Maldivian Rufiyaa' },
    { code: 'MWK', symbol: 'MK', label: 'Malawian Kwacha' },
    { code: 'MXN', symbol: '$', label: 'Mexican Peso' },
    { code: 'MYR', symbol: 'RM', label: 'Malaysian Ringgit' },
    { code: 'MZN', symbol: 'MT', label: 'Mozambican Metical' },
    { code: 'NAD', symbol: '$', label: 'Namibian Dollar' },
    { code: 'NIO', symbol: 'C$', label: 'Nicaraguan Córdoba' },
    { code: 'NOK', symbol: 'kr', label: 'Norwegian Krone' },
    { code: 'NPR', symbol: '₨', label: 'Nepalese Rupee' },
    { code: 'NZD', symbol: '$', label: 'New Zealand Dollar' },
    { code: 'OMR', symbol: 'ر.ع.', label: 'Omani Rial' },
    { code: 'PAB', symbol: 'B/.', label: 'Panamanian Balboa' },
    { code: 'PEN', symbol: 'S/.', label: 'Peruvian Sol' },
    { code: 'PGK', symbol: 'K', label: 'Papua New Guinean Kina' },
    { code: 'PHP', symbol: '₱', label: 'Philippine Peso' },
    { code: 'PKR', symbol: '₨', label: 'Pakistani Rupee' },
    { code: 'PLN', symbol: 'zł', label: 'Polish Złoty' },
    { code: 'PYG', symbol: 'Gs', label: 'Paraguayan Guarani' },
    { code: 'QAR', symbol: 'ر.ق', label: 'Qatari Rial' },
    { code: 'RON', symbol: 'lei', label: 'Romanian Leu' },
    { code: 'RSD', symbol: 'Дин.', label: 'Serbian Dinar' },
    { code: 'RUB', symbol: '₽', label: 'Russian Ruble' },
    { code: 'RWF', symbol: 'FRw', label: 'Rwandan Franc' },
    { code: 'SAR', symbol: 'ر.س', label: 'Saudi Riyal' },
    { code: 'SBD', symbol: '$', label: 'Solomon Islands Dollar' },
    { code: 'SCR', symbol: '₨', label: 'Seychellois Rupee' },
    { code: 'SDG', symbol: 'ج.س.', label: 'Sudanese Pound' },
    { code: 'SEK', symbol: 'kr', label: 'Swedish Krona' },
    { code: 'SGD', symbol: '$', label: 'Singapore Dollar' },
    { code: 'SHP', symbol: '£', label: 'St. Helena Pound' },
    { code: 'SLL', symbol: 'Le', label: 'Sierra Leonean Leone' },
    { code: 'SOS', symbol: 'S', label: 'Somali Shilling' },
    { code: 'SRD', symbol: '$', label: 'Surinamese Dollar' },
    { code: 'SSP', symbol: '£', label: 'South Sudanese Pound' },
    { code: 'STN', symbol: 'Db', label: 'São Tomé and Príncipe Dobra' },
    { code: 'SYP', symbol: '£', label: 'Syrian Pound' },
    { code: 'SZL', symbol: 'L', label: 'Swazi Lilangeni' },
    { code: 'THB', symbol: '฿', label: 'Thai Baht' },
    { code: 'TJS', symbol: 'SM', label: 'Tajikistani Somoni' },
    { code: 'TMT', symbol: 'T', label: 'Turkmenistani Manat' },
    { code: 'TND', symbol: 'د.ت', label: 'Tunisian Dinar' },
    { code: 'TOP', symbol: 'T$', label: 'Tongan Paʻanga' },
    { code: 'TRY', symbol: '₺', label: 'Turkish Lira' },
    { code: 'TTD', symbol: 'TT$', label: 'Trinidad and Tobago Dollar' },
    { code: 'TWD', symbol: 'NT$', label: 'New Taiwan Dollar' },
    { code: 'TZS', symbol: 'TSh', label: 'Tanzanian Shilling' },
    { code: 'UAH', symbol: '₴', label: 'Ukrainian Hryvnia' },
    { code: 'UGX', symbol: 'USh', label: 'Ugandan Shilling' },
    { code: 'UYU', symbol: '$U', label: 'Uruguayan Peso' },
    { code: 'UZS', symbol: 'soʻm', label: 'Uzbekistani Som' },
    { code: 'VES', symbol: 'Bs.S', label: 'Venezuelan Bolívar Soberano' },
    { code: 'VND', symbol: '₫', label: 'Vietnamese Đồng' },
    { code: 'VUV', symbol: 'VT', label: 'Vanuatu Vatu' },
    { code: 'WST', symbol: 'WS$', label: 'Samoan Tālā' },
    { code: 'XAF', symbol: 'FCFA', label: 'Central African CFA Franc' },
    { code: 'XCD', symbol: '$', label: 'East Caribbean Dollar' },
    { code: 'XOF', symbol: 'CFA', label: 'West African CFA Franc' },
    { code: 'XPF', symbol: '₣', label: 'CFP Franc' },
    { code: 'YER', symbol: '﷼', label: 'Yemeni Rial' },
    { code: 'ZMW', symbol: 'ZK', label: 'Zambian Kwacha' },
    { code: 'ZWL', symbol: 'Z$', label: 'Zimbabwean Dollar' },
];
